# Generated by Django 5.1.3 on 2025-02-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_usermoreinfo_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinfo',
            name='Profile_Picture',
            field=models.ImageField(upload_to='myapp'),
        ),
    ]
