# Generated by Django 5.1.6 on 2025-03-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_usermoreinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinfo',
            name='Profile_Picture',
            field=models.ImageField(blank=True, upload_to='P_pic'),
        ),
    ]
